<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
/**
 * ArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloRepository extends \Doctrine\ORM\EntityRepository {

    public function articulosCompletos() {

        $em = $this->getEntityManager();
        $query = $em->createQuery('select a FROM AppBundle:Articulo a');
        //añadir orderBy idSeccion
        $resultado = $query->getResult();

        return $resultado;
    }

    public function articulos($idSeccion) {

        if ($idSeccion == null) {
            throw new HttpNotFoundException('La sección no existe.');
        }

        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT art FROM AppBundle:Articulo art LEFT JOIN AppBundle:Imagenarticulo ia WHERE ia.idArticulo = art.id WHERE art.idSeccion = :idSeccion AND art.activo = :activo order by art.fecha desc')
                ->setParameter('idSeccion', $idSeccion)
                ->setParameter('activo', 1);
        $resultado = $query->getResult();

        return $resultado;
    }

    public function articulosPortada($idSeccion) {

        if ($idSeccion != null) {
            $em = $this->getEntityManager();
            $query = $em->createQuery('select a FROM AppBundle:Articulo a LEFT JOIN AppBundle:Imagenarticulo b WHERE b.idArticulo = a.id WHERE a.idSeccion = :idSeccion and a.mostrar = :mostrar')
                    ->setParameter('idSeccion', $idSeccion)
                    ->setParameter('mostrar', 1);
            $resultado = $query->getResult();

            return $resultado;
        }
    }

    public function articuloCompletoById($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('select a FROM AppBundle:Articulo a WHERE a.id = :id')->setParameter('id', $id);
        $resultado = $query->getResult();
        return $resultado;
    }

    public function getEvento() {
        $em = $this->getEntityManager();

        $query = $em->createQuery('select a,b,s FROM AppBundle:Articulo a LEFT JOIN AppBundle:Imagenarticulo b WHERE b.idArticulo = a.id
        LEFT JOIN AppBundle:Subarticulo s WHERE s.idArticulo = a.id WHERE s.isEvento = :isEvento')
        ->setParameter('isEvento', 1);
        
        $resultado = $query->getResult();
        $evento = null;
        if(!empty($resultado)) {
            $e = [
                "Articulo" => $resultado[0],
                "Imagenarticulo" => $resultado[1],
                "Subarticulo" => $resultado[2],            
            ];
            $evento = [
                "subartid" => $e["Subarticulo"]->getId(),
                "rutaimg" => $e["Imagenarticulo"]->getRuta(),
                "descripcion" => $e["Articulo"]->getContenidoBreve(),
            ];
        }
        dump($evento);
        return $evento;       
    }
}
