<?php

namespace AppBundle\Repository;

/**
 * ClientesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActivos()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT c FROM AppBundle:Clientes c WHERE c.activo = :activo")->setParameter('activo',1);
        $resultado = $query->getResult();
        
        return $resultado;
    }
}
