<?php

namespace AppBundle\Repository;

/**
 * imagenArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class imagenArticuloRepository extends \Doctrine\ORM\EntityRepository
{
}
