<?php

namespace AppBundle\Repository;

/**
 * ImagenarticulooRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagenarticuloRepository extends \Doctrine\ORM\EntityRepository
{
}
