<?php

namespace AppBundle\Repository;

/**
 * SubarticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubarticuloRepository extends \Doctrine\ORM\EntityRepository {

    public function subarticulo($idArt) {

        $em = $this->getEntityManager();
        //$query = $em->createQuery('select a FROM AppBundle:Subarticulo a LEFT JOIN AppBundle:imagenArticulo b where b.idArticulo = a.idArticulo WHERE a.idArticulo = :idArt')->setParameter('idArt', $idArt);
        $query = $em->createQuery('select s FROM AppBundle:Subarticulo s WHERE s.idArticulo = :idArt')->setParameter('idArt', $idArt);
        $resultado = $query->getResult();

        return $resultado;
    }
    
    public function listaSubarticulos() {

        $em = $this->getEntityManager();
        $query = $em->createQuery('select s FROM AppBundle:Subarticulo s WHERE s.activo = :activo')->setParameter('activo', 1);
        $resultado = $query->getResult();

        return $resultado;
    }
}
